// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOkUJG7HahHfeybKUETeJIYcUDUR99zs',
    appId: '1:198219726304:web:00ac62be3fc7154d4b3f85',
    messagingSenderId: '198219726304',
    projectId: 'scrumboardopgave',
    authDomain: 'scrumboardopgave.firebaseapp.com',
    databaseURL: 'https://scrumboardopgave-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scrumboardopgave.appspot.com',
    measurementId: 'G-RHFN02SZGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5dSkA0UidQpZpwBQvhPYPvmOpwO9-DtU',
    appId: '1:198219726304:android:4b8f725f01db25fd4b3f85',
    messagingSenderId: '198219726304',
    projectId: 'scrumboardopgave',
    databaseURL: 'https://scrumboardopgave-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scrumboardopgave.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCw3pj9hKXrTnSCccFhZhOlmb0wy2SboQ',
    appId: '1:198219726304:ios:68d14ab84dae229a4b3f85',
    messagingSenderId: '198219726304',
    projectId: 'scrumboardopgave',
    databaseURL: 'https://scrumboardopgave-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scrumboardopgave.appspot.com',
    iosClientId: '198219726304-3rgh4tk6kqolf7pah69tg0tb696i5roh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCw3pj9hKXrTnSCccFhZhOlmb0wy2SboQ',
    appId: '1:198219726304:ios:68d14ab84dae229a4b3f85',
    messagingSenderId: '198219726304',
    projectId: 'scrumboardopgave',
    databaseURL: 'https://scrumboardopgave-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scrumboardopgave.appspot.com',
    iosClientId: '198219726304-3rgh4tk6kqolf7pah69tg0tb696i5roh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
